// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi2S3C5CvsWDHSrBKVHur6d-ZKoy9BBDs',
    appId: '1:292082456056:web:1bdb741ce4ed1e0d4ff20d',
    messagingSenderId: '292082456056',
    projectId: 'cartcraze-9c761',
    authDomain: 'cartcraze-9c761.firebaseapp.com',
    storageBucket: 'cartcraze-9c761.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvkwgyfxSwpgJU9WU_4SzaT5dHxeFwYmc',
    appId: '1:292082456056:android:16d4101a562476444ff20d',
    messagingSenderId: '292082456056',
    projectId: 'cartcraze-9c761',
    storageBucket: 'cartcraze-9c761.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnVtfXiCzKCLa2qmV-yWAruJM9xTCRyVc',
    appId: '1:292082456056:ios:3c0fcc7ab0227ec84ff20d',
    messagingSenderId: '292082456056',
    projectId: 'cartcraze-9c761',
    storageBucket: 'cartcraze-9c761.firebasestorage.app',
    iosBundleId: 'com.example.cartcraze',
  );
}
